=== HumanCellAtlas/metadata-schema/json_schema/type/biomaterial/cell_suspension.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Information about the suspension of cells or nuclei derived from the collected or cultured specimen.",
    "additionalProperties": false,
    "required": [
        "describedBy",
        "schema_type",
        "biomaterial_core"
    ],
    "title": "Cell suspension",
    "name": "cell_suspension",
    "type": "object",
    "properties": {
        "describedBy":  {
            "description": "The URL reference to the schema.",
            "type": "string",
            "pattern" : "^(http|https)://schema.(.*?)humancellatlas.org/type/biomaterial/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/cell_suspension"
        },
        "schema_version": {
            "description": "The version number of the schema in major.minor.patch format.",
            "type": "string",
            "pattern": "^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$",
            "example": "4.6.1"
        },
        "schema_type": {
            "description": "The type of the metadata schema entity.",
            "type": "string",
            "enum": [
                "biomaterial"
            ]
        },
        "provenance" : {
            "description": "Provenance information provided by the system.",
            "type": "object",
            "$ref": "system/provenance.json"
        },
        "biomaterial_core" : {
            "description": "Core biomaterial-level information.",
            "type": "object",
            "$ref": "core/biomaterial/biomaterial_core.json",
            "user_friendly": "Biomaterial core"
        },
        "cell_morphology": {
            "description": "Features relating to the morphology of cells in a biomaterial.",
            "type": "object",
            "$ref": "module/biomaterial/cell_morphology.json",
            "user_friendly": "Cell morphology"
        },
        "growth_conditions": {
            "description": "Features relating to the growth and/or maintenance of a biomaterial.",
            "type": "object",
            "$ref": "module/biomaterial/growth_conditions.json",
            "user_friendly": "Growth conditions"
        },
        "genus_species": {
            "description": "The scientific binomial name for the species of the suspension.",
            "type" : "array",
            "example": "Homo sapiens",
            "items":{
                "$ref": "module/ontology/species_ontology.json"
            },
            "user_friendly": "Genus species"
        },
        "selected_cell_type": {
            "description" : "The cell type(s) selected to be present in the suspension.",
            "type": "array",
            "items": {
		        "$ref": "module/ontology/cell_type_ontology.json"
	        },
            "user_friendly": "Selected cell type"
       },
        "total_estimated_cells": {
            "description": "Total estimated number of cells in the suspension. May be 1 for well-based assays.",
            "type": "integer",
            "maximum": 1000000000,
            "minimum": 0,
            "example": 2100,
            "user_friendly": "Total estimated cell count"
        },
        "plate_based_sequencing" : {
            "description": "Fields specific for plate-based sequencing experiments.",
            "type": "object",
            "$ref": "module/process/sequencing/plate_based_sequencing.json",
            "user_friendly": "Plate-based sequencing"
        }
     }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/CD4+ cytotoxic T lymphocytes/cell_suspension_0.json
{
    "describedBy": "http://schema.dev.data.humancellatlas.org/type/biomaterial/8.6.1/cell_suspension",
    "schema_type": "biomaterial",
    "biomaterial_core": {
        "biomaterial_id": "Single-cell_RNA-seq_Subject10_TEMRA_Cell001",
        "biomaterial_name": "Single-cell_RNA-seq_Subject10_TEMRA_Cell001",
        "biomaterial_description": "Single-cell_RNA-seq_Subject10_TEMRA_Cell001",
        "ncbi_taxon_id": [
            9606
        ],
        "insdc_biomaterial": "SRS2661967"
    },
    "genus_species": [
        {
            "text": "Homo sapiens",
            "ontology": "NCBITaxon:9606"
        }
    ],
    "selected_cell_type": [
        {
            "text": "TEMRA",
            "ontology": "CL:0000625"
        }
    ],
    "total_estimated_cells": 1,
    "plate_based_sequencing": {
        "plate_id": "subject9-10_batch1",
        "cell_quality": "OK"
    },
    "provenance": {
        "document_id": "cc0d9bf0-6ad5-4489-994b-db26ff761c5a",
        "submission_date": "2018-09-05T09:47:21.355Z",
        "update_date": "2018-09-05T09:53:09.415Z"
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/1M Immune Cells/cell_suspension_0.json
{
    "describedBy": "http://schema.dev.data.humancellatlas.org/type/biomaterial/8.6.1/cell_suspension",
    "schema_type": "biomaterial",
    "biomaterial_core": {
        "biomaterial_id": "1_BM1_cells",
        "ncbi_taxon_id": [
            9606
        ]
    },
    "genus_species": [
        {
            "text": "Homo sapiens",
            "ontology": "NCBITaxon:9606"
        }
    ],
    "selected_cell_type": [
        {
            "text": "bone marrow hematopoietic cell",
            "ontology": "CL:1001610"
        }
    ],
    "total_estimated_cells": 4294,
    "provenance": {
        "document_id": "7b53bae2-2424-44c0-9d80-ad72e8bca136",
        "submission_date": "2018-09-04T12:26:41.629Z",
        "update_date": "2018-09-04T12:27:19.625Z"
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/HPSI_human_cerebral_organoids/cell_suspension_0.json
{
    "describedBy": "http://schema.dev.data.humancellatlas.org/type/biomaterial/8.6.1/cell_suspension",
    "schema_type": "biomaterial",
    "biomaterial_core": {
        "biomaterial_id": "HPSI_organoids_pooled_1",
        "biomaterial_name": "pooled cells from 4 dissociated organoids",
        "biomaterial_description": "pooled cells from 4 dissociated organoids (wibj_2, kucg_2, hoik_1, sojd_3)",
        "ncbi_taxon_id": [
            9606
        ]
    },
    "genus_species": [
        {
            "text": "Homo sapiens",
            "ontology": "NCBITaxon:9606"
        }
    ],
    "selected_cell_type": [
        {
            "text": "neural cell",
            "ontology": "CL:0002319"
        }
    ],
    "total_estimated_cells": 6316,
    "provenance": {
        "document_id": "8fc8b364-98bb-4082-98af-e3fdffcf82b7",
        "submission_date": "2018-09-05T09:25:02.595Z",
        "update_date": "2018-09-05T09:25:12.353Z"
    }
}
