=== HumanCellAtlas/metadata-schema/json_schema/type/protocol/sequencing/library_preparation_protocol.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Information about how a sequencing library was prepared.",
    "additionalProperties": false,
    "required": [
        "describedBy",
        "schema_type",
        "protocol_core",
        "end_bias",
        "library_construction_approach",
        "strand",
        "input_nucleic_acid_molecule"
    ],
    "title": "Library preparation protocol",
    "name": "library_preparation_protocol",
    "type": "object",
    "properties": {
         "describedBy":  {
            "description": "The URL reference to the schema.",
            "type": "string",
            "pattern" : "^(http|https)://schema.(.*?)humancellatlas.org/type/protocol/sequencing/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/library_preparation_protocol"
        },
        "schema_version": {
            "description": "The version number of the schema in major.minor.patch format.",
            "type": "string",
            "pattern": "^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$",
            "example": "4.6.1"
        },
        "schema_type": {
            "description": "The type of the metadata schema entity.",
            "type": "string",
            "enum": [
                "protocol"
            ]
        },
        "provenance" : {
            "description": "Provenance information provided by the system.",
            "type": "object",
            "$ref": "system/provenance.json"
        },
        "protocol_core" : {
            "description": "Core protocol-level information.",
            "type": "object",
            "$ref": "core/protocol/protocol_core.json"
        },
        "cell_barcode": {
            "description": "Information about cell identifier barcodes.",
            "type": "object",
            "$ref": "module/process/sequencing/barcode.json",
            "user_friendly": "Cell barcode"
        },
        "input_nucleic_acid_molecule": {
            "description": "Starting nucleic acid molecule isolated for sequencing.",
            "type": "object",
            "$ref": "module/ontology/biological_macromolecule_ontology.json",
            "user_friendly": "Input nucleic acid molecule",
            "example": "polyA RNA"
        },
        "nucleic_acid_source": {
            "description": "Source cells or organelles from which nucleic acid molecules were collected.",
            "type": "string",
            "enum": [
                "bulk cell",
                "single cell",
                "single nucleus",
                "bulk nuclei",
                "mitochondria"
            ],
            "user_friendly": "Nucleic acid source",
            "example": "Should be one of: bulk cell, single cell, single nucleus, bulk nuclei, or mitochondria."
        },
        "library_construction_approach": {
            "description": "The general approach for sequencing library construction.",
            "type": "object",
            "$ref": "module/ontology/library_construction_ontology.json",
            "user_friendly": "Library construction approach",
            "example": "Smart-seq2"
        },
        "library_construction_kit": {
            "description": "Name of kit used to construct the sequencing library.",
            "type": "object",
            "$ref": "module/process/purchased_reagents.json",
            "user_friendly": "Library construction kit"
        },
        "nucleic_acid_conversion_kit": {
            "description": "Name of kit used to convert RNA to DNA for sequencing.",
            "type": "object",
            "$ref": "module/process/purchased_reagents.json",
            "user_friendly": "Nucleic acid conversion kit"
        },
        "end_bias": {
            "description": "The type of tag or end bias the library has.",
            "type": "string",
            "example": "Should be one of: 3 prime tag, 3 prime end bias, 5 prime tag, 5 prime end bias, or full length.",
            "enum": [
                "3 prime tag",
                "3 prime end bias",
                "5 prime tag",
                "5 prime end bias",
                "full length"
            ],
            "user_friendly": "End bias"
        },
        "primer": {
            "description": "Primer used for cDNA synthesis from RNA.",
            "type": "string",
            "enum": [
                "poly-dT",
                "random"
            ],
            "user_friendly": "Primer",
            "example": "Should be one of: poly-dT, or random."
        },
        "strand": {
            "description": "Library strandedness.",
            "type": "string",
            "enum": [
                "first",
                "second",
                "unstranded",
                "not provided"
            ],
            "example": "Should be one of: first, second, or unstranded.",
            "user_friendly": "Strand"
        },
        "spike_in_kit": {
            "description": "Information about a spike-in kit, if used.",
            "type": "object",
            "$ref": "module/process/purchased_reagents.json",
            "user_friendly": "Spike-in kit"
        },
        "spike_in_dilution": {
            "description": "Dilution of spike-in, if used.",
            "type": "integer",
            "maximum": 1000000,
            "minimum": 1,
            "user_friendly": "Spike-in dilution",
            "example": 100
        },
        "umi_barcode": {
            "description": "Information about unique molecular identifier (UMI) barcodes.",
            "type": "object",
            "$ref": "module/process/sequencing/barcode.json",
            "user_friendly": "UMI barcode"
        },
        "library_preamplification_method": {
            "description": "The method used to amplify RNA prior to adaptor ligation.",
            "type": "object",
            "$ref": "module/ontology/library_amplification_ontology.json",
            "user_friendly": "Library pre-amplification method",
            "example": "PCR"
        },
        "cdna_library_amplification_method": {
            "description": "The method used to amplify a cDNA library prior to sequencing.",
            "type": "object",
            "$ref": "module/ontology/library_amplification_ontology.json",
            "user_friendly": "cDNA library amplification method",
            "example": "PCR"
        }
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/Tissue stability/library_preparation_protocol_cc50851b-4c12-463b-b527-60d1c8d5ef60.json.json
{
    "describedBy": "http://schema.dev.data.humancellatlas.org/type/protocol/sequencing/4.3.2/library_preparation_protocol",
    "schema_type": "protocol",
    "protocol_core": {
        "protocol_id": "library_preparation_protocol_1",
        "protocol_name": "Library preparation for 10x_v2 sequencing",
        "protocol_description": "ChromiumTM Single Cell 3' Library & Gel Bead Kit v2",
        "document": "10x_sequencing_protocol.pdf"
    },
    "cell_barcode": {
        "barcode_read": "Read 1",
        "barcode_offset": 0,
        "barcode_length": 16
    },
    "input_nucleic_acid_molecule": {
        "text": "polyA RNA",
        "ontology": "OBI:0000869"
    },
    "library_construction_approach": {
        "text": "10X sequencing",
        "ontology": "EFO:0008995"
    },
    "nucleic_acid_source": "single cell",
    "end_bias": "3 prime tag",
    "strand": "second",
    "umi_barcode": {
        "barcode_read": "Read 1",
        "barcode_offset": 16,
        "barcode_length": 10
    },
    "provenance": {
        "document_id": "cc50851b-4c12-463b-b527-60d1c8d5ef60",
        "submission_date": "2018-09-05T09:14:54.945Z",
        "update_date": "2018-09-05T09:15:02.223Z"
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/1M Immune Cells/library_preparation_protocol_e4024c4a-dbce-4bda-bed8-21414091e7ce.json.json
{
    "describedBy": "http://schema.dev.data.humancellatlas.org/type/protocol/sequencing/4.3.2/library_preparation_protocol",
    "schema_type": "protocol",
    "protocol_core": {
        "protocol_id": "library_preparation_protocol_1",
        "protocol_name": "Preparing RNA for sequencing by 10x"
    },
    "cell_barcode": {
        "barcode_read": "Read 1",
        "barcode_offset": 0,
        "barcode_length": 16
    },
    "input_nucleic_acid_molecule": {
        "text": "polyA RNA",
        "ontology": "OBI:0000869"
    },
    "library_construction_approach": {
        "text": "10X sequencing",
        "ontology": "EFO:0008995"
    },
    "nucleic_acid_source": "single cell",
    "end_bias": "3 prime tag",
    "primer": "poly-dT",
    "strand": "second",
    "umi_barcode": {
        "barcode_read": "Read 1",
        "barcode_offset": 16,
        "barcode_length": 10
    },
    "provenance": {
        "document_id": "e4024c4a-dbce-4bda-bed8-21414091e7ce",
        "submission_date": "2018-09-04T12:26:54.992Z",
        "update_date": "2018-09-04T12:27:50.909Z"
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/HPSI_human_cerebral_organoids/library_preparation_protocol_0.json
{
    "describedBy": "http://schema.dev.data.humancellatlas.org/type/protocol/sequencing/4.3.2/library_preparation_protocol",
    "schema_type": "protocol",
    "protocol_core": {
        "protocol_id": "10x_3'_library_preparation",
        "protocol_name": "10x 3' single cell library preparation",
        "protocol_description": "10x Chromium single cell 3' v2 library preparation",
        "document": "CG00052_SingleCell3_ReagentKitv2UserGuide_RevE.pdf"
    },
    "nucleic_acid_source": "single cell",
    "input_nucleic_acid_molecule": {
        "text": "polyA RNA",
        "ontology": "OBI:0000869"
    },
    "library_construction_approach": {
        "text": "Chromium 3' Single Cell v2",
        "ontology": "EFO:0008995"
    },
    "end_bias": "3 prime end bias",
    "primer": "poly-dT",
    "strand": "unstranded",
    "cell_barcode": {
        "barcode_read": "Read 1",
        "barcode_offset": 0,
        "barcode_length": 16
    },
    "umi_barcode": {
        "barcode_read": "Read 1",
        "barcode_offset": 15,
        "barcode_length": 10
    },
    "library_construction_kit": {
        "retail_name": "10X Chromium Single Cell 3' Solution v2 Chemistry",
        "manufacturer": "10X Genomics"
    },
    "provenance": {
        "document_id": "853c2086-1ac4-488e-b3b3-fe7956e74283",
        "submission_date": "2018-09-05T09:25:02.667Z",
        "update_date": "2018-09-05T09:25:09.008Z"
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/vX/Q4DemoSS2/library_preparation_protocol_0.json
{
    "describedBy": "https://schema.humancellatlas.org/type/protocol/sequencing/3.0.0/library_preparation_protocol",
    "schema_type": "protocol",
    "protocol_core": {
        "protocol_id": "preparation1"
    },
    "input_nucleic_acid_molecule": {
        "text": "polyA RNA"
    },
    "library_construction_approach": {
        "text": "Smart-seq2",
        "ontology": "EFO:0008931"
    },
    "end_bias": "5 prime end bias",
    "strand": "unstranded",
    "provenance": {
        "document_id": "6603e237-9f5d-4a40-88b8-8df65474a794",
        "submission_date": "2018-07-22T23:38:36.171Z",
        "update_date": "2018-07-22T23:38:44.032Z"
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/Mouse Melanoma/library_preparation_protocol_38e07040-6198-4a46-b195-88c0680ef283.json.json
{
    "describedBy": "http://schema.dev.data.humancellatlas.org/type/protocol/sequencing/4.3.2/library_preparation_protocol",
    "schema_type": "protocol",
    "protocol_core": {
        "protocol_id": "SmartSeq2_RTPCR_protocol",
        "protocol_name": "Make/amplify cDNA for each cell",
        "document": "SmartSeq2_RTPCR_protocol.pdf"
    },
    "nucleic_acid_source": "single cell",
    "input_nucleic_acid_molecule": {
        "text": "polyA RNA",
        "ontology": "OBI:0000869"
    },
    "library_construction_approach": {
        "text": "Smart-seq2",
        "ontology": "EFO:0008931"
    },
    "end_bias": "full length",
    "primer": "poly-dT",
    "strand": "unstranded",
    "umi_barcode": {
        "barcode_read": "Read 1",
        "barcode_offset": 0,
        "barcode_length": 16
    },
    "provenance": {
        "document_id": "38e07040-6198-4a46-b195-88c0680ef283",
        "submission_date": "2018-09-04T12:53:51.109Z",
        "update_date": "2018-09-04T12:55:56.069Z"
    }
}
