=== HumanCellAtlas/metadata-schema/json_schema/core/links.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A schema for a links bundle.",
  "additionalProperties": false,
  "required": [
    "describedBy",
    "schema_type"
  ],
  "title": "links",
  "type": "object",
  "definitions": {
      "bundle_links": {
         "type": "object",
         "properties": {
          "source_type": {
            "description": "The type of the entity this link starts from",
            "type": "string"
          },
          "source_id": {
            "description": "The id of the entity this link starts from",
            "type": "string"
          },
          "destination_type": {
            "description": "The type of the entity this link goes to",
            "type": "string"
          },
          "destination_id": {
            "description": "The id  of the entity this link goes to",
            "type": "string"
          }
        }
      }
  },
  "properties": {
    "describedBy": {
      "description": "The URL reference to the schema.",
      "type": "string",
      "pattern": "^(http|https)://schema.(.*?)humancellatlas.org/core/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/links"
    },
    "schema_version": {
      "description": "The version number of the schema in major.minor.patch format.",
      "type": "string",
      "pattern": "^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$"
    },
    "schema_type": {
      "description": "The type of the metadata schema entity.",
      "type": "string",
      "enum": [
        "link_bundle"
      ]
    },
    "links": {
      "description": "An array of linking objects",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "core/links.json#/definitions/bundle_links"
      }
    }
  }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/Single cell transcriptome analysis of human pancreas/links_0.json
{
    "describedBy": "https://schema.humancellatlas.org/system/1.1.1/links",
    "schema_type": "link_bundle",
    "schema_version": "1.1.1",
    "links": [
        {
            "process": "5f868fc6-dc13-4f06-a82e-ff83497d03ee",
            "inputs": [
                "c61125ab-d5e0-4d93-b0a7-2deac1729f65"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "0494ee09-b1e2-437a-986f-06d5df4a6858",
                "baf745cd-9052-4a6c-8c1a-919390062c09"
            ],
            "output_type": "file",
            "protocols": [
                {
                    "protocol_type": "library_preparation_protocol",
                    "protocol_id": "34c6db60-ef27-4502-9191-102d1a235adc"
                },
                {
                    "protocol_type": "sequencing_protocol",
                    "protocol_id": "319dd8c8-e9d6-40df-bf72-e0423f4f5418"
                }
            ]
        },
        {
            "process": "6c357ba8-bd9a-41cb-9d74-b9442efb7217",
            "inputs": [
                "07282a68-dca4-449e-81b6-7b0da34230df"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "c61125ab-d5e0-4d93-b0a7-2deac1729f65"
            ],
            "output_type": "biomaterial",
            "protocols": []
        },
        {
            "process": "0aede7bd-0a5d-4dc5-a8e8-2d4ad6d01bfb",
            "inputs": [
                "cd379b0c-7b23-4093-b0b0-65d592ab2839"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "07282a68-dca4-449e-81b6-7b0da34230df"
            ],
            "output_type": "biomaterial",
            "protocols": []
        }
    ]
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/HPSI_human_cerebral_organoids/links_919fea96-8ee2-4406-98c0-8ed91c8fb93f.json.json
{
    "describedBy": "https://schema.humancellatlas.org/system/1.1.1/links",
    "schema_type": "link_bundle",
    "schema_version": "1.1.1",
    "links": [
        {
            "process": "88ef68b1-0c0b-4594-be46-4bb0bcf2025d",
            "inputs": [
                "8fc8b364-98bb-4082-98af-e3fdffcf82b7"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "740b2221-41c6-498d-87de-8b2937a5ebed",
                "a3f614b3-e6cf-4751-a15d-ff623efea62a",
                "56c2a158-e389-40a3-97a7-0f2966a393b8"
            ],
            "output_type": "file",
            "protocols": [
                {
                    "protocol_type": "library_preparation_protocol",
                    "protocol_id": "853c2086-1ac4-488e-b3b3-fe7956e74283"
                },
                {
                    "protocol_type": "sequencing_protocol",
                    "protocol_id": "0b1dfbd4-1fbe-42a4-9213-b66dac4d4ac0"
                }
            ]
        },
        {
            "process": "d3c8ba6e-e552-48cc-ab34-38a95712b3f7",
            "inputs": [
                "77a87953-5d2d-4e22-9c8b-c012fa8656b9",
                "e4307721-7d92-4f92-a6f1-6f1d4ecf1835",
                "08936dad-6f12-4f43-8bd2-b6863f166a21",
                "dfd95ce4-c5be-4175-9e9a-249b1b09f5d9"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "8fc8b364-98bb-4082-98af-e3fdffcf82b7"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "dissociation_protocol",
                    "protocol_id": "58334256-af4f-4754-9455-668fb31bbcff"
                }
            ]
        },
        {
            "process": "3ef770a1-1f72-47f2-952e-9fd584e74598",
            "inputs": [
                "cc5c8bd6-3bd6-49d6-87b3-b24ef3a577a4"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "77a87953-5d2d-4e22-9c8b-c012fa8656b9"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "differentiation_protocol",
                    "protocol_id": "537b3c44-998f-43c2-8146-7e3e2932c30b"
                }
            ]
        },
        {
            "process": "1c4b3da5-41c3-40bd-b128-4a4a94fb876e",
            "inputs": [
                "440a306a-54c6-4193-9b60-ad4423c8a62b"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "cc5c8bd6-3bd6-49d6-87b3-b24ef3a577a4"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "ipsc_induction_protocol",
                    "protocol_id": "9e3b5ef9-cbb0-43ef-a194-1ce1969cfd62"
                }
            ]
        },
        {
            "process": "359f3d8c-e29c-41f1-b058-1854a7d7e79e",
            "inputs": [
                "eea3dd19-90e0-45c4-803d-4620d1fab90d"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "440a306a-54c6-4193-9b60-ad4423c8a62b"
            ],
            "output_type": "biomaterial",
            "protocols": []
        },
        {
            "process": "df40cef2-60ae-400c-bece-947329b40946",
            "inputs": [
                "304fadde-e22a-4ff9-9544-f8ec097b6135"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "e4307721-7d92-4f92-a6f1-6f1d4ecf1835"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "differentiation_protocol",
                    "protocol_id": "537b3c44-998f-43c2-8146-7e3e2932c30b"
                }
            ]
        },
        {
            "process": "0ec71414-3c56-4347-85a2-a2b66a4a147d",
            "inputs": [
                "4eb07fdb-dcd8-4805-89ad-6068071c80c9"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "304fadde-e22a-4ff9-9544-f8ec097b6135"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "ipsc_induction_protocol",
                    "protocol_id": "9e3b5ef9-cbb0-43ef-a194-1ce1969cfd62"
                }
            ]
        },
        {
            "process": "9c2903a9-d93e-41a4-88bf-61647c6990a6",
            "inputs": [
                "fbd4c071-58bd-4818-8ddd-2c31ddb60363"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "4eb07fdb-dcd8-4805-89ad-6068071c80c9"
            ],
            "output_type": "biomaterial",
            "protocols": []
        },
        {
            "process": "1ff79cfa-57e9-4af1-a754-51bdf36c4414",
            "inputs": [
                "8bd345cb-4635-4bf5-9435-bf144013b938"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "08936dad-6f12-4f43-8bd2-b6863f166a21"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "differentiation_protocol",
                    "protocol_id": "537b3c44-998f-43c2-8146-7e3e2932c30b"
                }
            ]
        },
        {
            "process": "94b7d3a9-2a09-40d1-ba0e-80e8410b3d55",
            "inputs": [
                "54046c37-b50d-41ae-a95f-2db29b1b706b"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "8bd345cb-4635-4bf5-9435-bf144013b938"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "ipsc_induction_protocol",
                    "protocol_id": "9e3b5ef9-cbb0-43ef-a194-1ce1969cfd62"
                }
            ]
        },
        {
            "process": "85e8adfd-f23b-47fb-9617-e51593923405",
            "inputs": [
                "62ee5119-4fa1-4508-95f3-59c7b0fddd34"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "54046c37-b50d-41ae-a95f-2db29b1b706b"
            ],
            "output_type": "biomaterial",
            "protocols": []
        },
        {
            "process": "f999e1a4-31fc-4298-b958-8f567511935e",
            "inputs": [
                "6953e086-13cc-4467-b059-4d5f91f6f268"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "dfd95ce4-c5be-4175-9e9a-249b1b09f5d9"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "differentiation_protocol",
                    "protocol_id": "537b3c44-998f-43c2-8146-7e3e2932c30b"
                }
            ]
        },
        {
            "process": "4e60bff4-9ede-42e2-9152-7f8f445938f5",
            "inputs": [
                "2b541914-778d-4b24-9680-9d2643cfeff9"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "6953e086-13cc-4467-b059-4d5f91f6f268"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "ipsc_induction_protocol",
                    "protocol_id": "9e3b5ef9-cbb0-43ef-a194-1ce1969cfd62"
                }
            ]
        },
        {
            "process": "6ecf593a-c3d6-42a8-bf4e-a47549e7bb1f",
            "inputs": [
                "5554b939-a268-4619-9cef-0f09151454fc"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "2b541914-778d-4b24-9680-9d2643cfeff9"
            ],
            "output_type": "biomaterial",
            "protocols": []
        }
    ]
}

=== HumanCellAtlas/metadata-schema/examples/bundles/v5/GlioblastomaSS2/quakeGlioblastoma1_links_bundle_1.json
{
    "links": [
        {
            "source_id": "7c72f20a-8199-497a-bba7-1316520ba847", 
            "source_type": "biomaterial", 
            "destination_id": "336c7184-70a7-41b3-ab31-98f78b0ab092", 
            "destination_type": "dissociation_process"
        }, 
        {
            "source_id": "336c7184-70a7-41b3-ab31-98f78b0ab092", 
            "source_type": "dissociation_process", 
            "destination_id": "317d865b-1d94-439d-a1bc-0da63bbe2348", 
            "destination_type": "biomaterial"
        }, 
        {
            "source_id": "8c01ac9e-751b-4426-9032-c4235503a164", 
            "source_type": "process", 
            "destination_id": "7c72f20a-8199-497a-bba7-1316520ba847", 
            "destination_type": "biomaterial"
        }, 
        {
            "source_id": "cd9d52fa-e89d-4c37-bb0e-997a2affe1dc", 
            "source_type": "biomaterial", 
            "destination_id": "8c01ac9e-751b-4426-9032-c4235503a164", 
            "destination_type": "process"
        }, 
        {
            "source_id": "412d2e81-18e0-4f23-b6ff-d579882d8efd", 
            "source_type": "sequencing_process", 
            "destination_id": "317d865b-1d94-439d-a1bc-0da63bbe2348", 
            "destination_type": "biomaterial"
        }, 
        {
            "source_id": "412d2e81-18e0-4f23-b6ff-d579882d8efd", 
            "source_type": "sequencing_process", 
            "destination_id": "54da508d-cf88-42da-8443-e623ef9ab94a", 
            "destination_type": "file"
        }, 
        {
            "source_id": "412d2e81-18e0-4f23-b6ff-d579882d8efd", 
            "source_type": "sequencing_process", 
            "destination_id": "9be3faa9-597f-453c-b42e-c83c70a8ebfe", 
            "destination_type": "file"
        }
    ], 
    "describedBy": "https://schema.humancellatlas.org/bundle/1.0.0/links", 
    "schema_version": "1.0.0", 
    "schema_type": "link_bundle"
}

=== HumanCellAtlas/metadata-schema/examples/bundles/public-beta/Healthy and type 2 diabetes pancreas/links.json
{
    "describedBy": "https://schema.humancellatlas.org/system/1.1.1/links",
    "schema_type": "link_bundle",
    "schema_version": "1.1.1",
    "links": [
        {
            "process": "aa67d2ed-e4ea-4cdf-92ed-7d5e6dc1f6fa",
            "inputs": [
                "1200f5bf-7d45-4f26-865e-b560797f1808"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "60471337-a47b-4b9c-95e7-4a19349a5e05"
            ],
            "output_type": "file",
            "protocols": [
                {
                    "protocol_type": "library_preparation_protocol",
                    "protocol_id": "079bc155-71c9-45ab-bd12-cab025890d82"
                },
                {
                    "protocol_type": "sequencing_protocol",
                    "protocol_id": "3aece946-4be6-4a0c-af23-ac884a87bcbb"
                }
            ]
        },
        {
            "process": "443b4672-3f14-4f1e-b7be-862ae02493dc",
            "inputs": [
                "38002d8f-eac5-4ee4-8290-03d323bf780e"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "1200f5bf-7d45-4f26-865e-b560797f1808"
            ],
            "output_type": "biomaterial",
            "protocols": [
                {
                    "protocol_type": "dissociation_protocol",
                    "protocol_id": "6029a289-861c-4349-9614-4c244103be21"
                }
            ]
        },
        {
            "process": "738243c5-e336-4c55-a8b6-b192b6f98fe7",
            "inputs": [
                "8bb4258a-90c7-4af6-8a1b-c4ab6c5483e2"
            ],
            "input_type": "biomaterial",
            "outputs": [
                "38002d8f-eac5-4ee4-8290-03d323bf780e"
            ],
            "output_type": "biomaterial",
            "protocols": []
        }
    ]
}
