=== HumanCellAtlas/metadata-schema/json_schema/bundle/file.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://schema.humancellatlas.org/bundle/1.0.0/file",
    "description": "A schema for a file bundle.",
    "additionalProperties": false,
    "required": [
        "describedBy",
        "schema_type"
    ],
    "title": "file",
    "type": "object",
    "definitions": {
        "file_ingest": {
            "required": [
                "hca_ingest",
                "content"
            ],
            "type": "object",
            "properties": {
                "hca_ingest": {
                    "description": "Core fields added by HCA ingest service",
                    "type": "object",
                    "$ref": "https://schema.humancellatlas.org/bundle/5.0.0/ingest_audit"
                },
                "content": {
                    "description": "Content for any file type entity.",
                    "type": "object",
                    "oneOf": [
                        { "$ref": "https://schema.humancellatlas.org/type/file/5.0.0/sequence_file" },
                        { "$ref": "https://schema.humancellatlas.org/type/file/5.0.0/analysis_file" }
                    ]
                }
            }
        }
    },
    "properties": {
        "describedBy" : {
            "description": "The URL reference to the schema.",
            "type": "string",
            "pattern" : "https://schema.humancellatlas.org/bundle/[0-9]{1,}.[0-9]{1,}.[0-9]{1,}/file"
        },
        "schema_version": {
            "description": "The version number of the schema in major.minor.patch format.",
            "type": "string",
            "pattern": "^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$"
        },
        "schema_type": {
            "description": "The type of the metadata schema entity.",
            "type": "string",
            "enum": [
                "file_bundle"
            ]
        },
        "files": {
            "description": "An array of files.",
            "type": "array",
            "items": {
                "$ref": "https://schema.humancellatlas.org/bundle/1.0.0/file#/definitions/file_ingest"
            }
        }
    }
}

=== HumanCellAtlas/metadata-schema/examples/bundles/v5/Q4DemoSS2/files.json
{
  "describedBy": "https://schema.humancellatlas.org/bundle/1.0.0/file",
  "schema_version": "1.0.0",
  "schema_type": "file_bundle",
  "files": [
    {
      "content": {
        "describedBy": "https://schema.humancellatlas.org/type/file/5.0.0/sequence_file",
        "schema_version": "5.0.0",
        "schema_type": "file",
        "file_core": {
          "file_name": "R1.fastq.gz",
          "file_format": "fastq.gz",
          "describedBy": "https://schema.humancellatlas.org/core/file/5.0.0/file_core",
          "schema_version": "5.0.0"
        },
        "read_index": "read1",
        "lane_index": 1,
        "read_length": 187
      },
      "hca_ingest": {
        "describedBy": "https://schema.humancellatlas.org/bundle/5.0.0/ingest_audit",
        "document_id": "db08d9a7-1fcb-4650-8892-6eee95877c42",
        "submissionDate": "2018-02-07T10:21:43.228Z",
        "updateDate": "2018-02-07T10:21:54.398Z",
        "submitter_id": "anonymousUser",
        "updater_id": "anonymousUser"
      }
    },
    {
      "content": {
        "describedBy": "https://schema.humancellatlas.org/type/file/5.0.0/sequence_file",
        "schema_version": "5.0.0",
        "schema_type": "file",
        "file_core": {
          "file_name": "R2.fastq.gz",
          "file_format": "fastq.gz",
          "describedBy": "https://schema.humancellatlas.org/core/file/5.0.0/file_core",
          "schema_version": "5.0.0"
        },
        "read_index": "read2",
        "lane_index": 1,
        "read_length": 225
      },
      "hca_ingest": {
        "describedBy": "https://schema.humancellatlas.org/bundle/5.0.0/ingest_audit",
        "document_id": "5266a514-5614-420e-a882-a9dff3df9d84",
        "submissionDate": "2018-02-07T10:21:43.228Z",
        "updateDate": "2018-02-07T10:21:54.398Z",
        "submitter_id": "anonymousUser",
        "updater_id": "anonymousUser"
      }
    }
  ]
}

=== HumanCellAtlas/metadata-schema/examples/bundles/v5/Q4DemoSS2/Q4_DEMO-project_PRJNA248302_file_bundle.json
{
    "files": [
        {
            "content": {
                "file_core": {
                    "file_name": "R1.fastq.gz", 
                    "file_format": "fastq.gz"
                }, 
                "lane_index": 1, 
                "read_index": "read1", 
                "describedBy": "https://schema.humancellatlas.org/type/file/5.1.0/sequence_file", 
                "schema_type": "file"
            }, 
            "hca_ingest": {
                "submissionDate": "2018-03-22T10:47:49.282Z", 
                "document_id": "621e28f3-4fbe-4d0f-b750-438883b19b15"
            }
        }, 
        {
            "content": {
                "file_core": {
                    "file_name": "R2.fastq.gz", 
                    "file_format": "fastq.gz"
                }, 
                "lane_index": 1, 
                "read_index": "read2", 
                "describedBy": "https://schema.humancellatlas.org/type/file/5.1.0/sequence_file", 
                "schema_type": "file"
            }, 
            "hca_ingest": {
                "submissionDate": "2018-03-22T10:47:49.290Z", 
                "document_id": "a6a4995f-2975-4935-855f-66e8e143e1b2"
            }
        }
    ], 
    "describedBy": "https://schema.humancellatlas.org/bundle/1.0.0/file", 
    "schema_version": "1.0.0", 
    "schema_type": "file_bundle"
}
