=== HumanCellAtlas/metadata-schema/json_schema/type/protocol/biomaterial_collection/enrichment_protocol.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Information about how a biomaterial is enriched for a feature or characteristic of interest.",
    "additionalProperties": false,
    "required": [
        "describedBy",
        "schema_type",
        "protocol_core",
        "method"
    ],
    "title": "Enrichment protocol",
    "name": "enrichment_protocol",
    "type": "object",
    "properties": {
        "describedBy":  {
            "description": "The URL reference to the schema.",
            "type": "string",
            "pattern" : "^(http|https)://schema.(.*?)humancellatlas.org/type/protocol/biomaterial_collection/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/enrichment_protocol"
        },
        "schema_version": {
            "description": "The version number of the schema in major.minor.patch format.",
            "type": "string",
            "pattern": "^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$",
            "example": "4.6.1"
        },
        "schema_major_version": {
            "description": "The major version number of the schema.",
            "type": "integer",
            "pattern": "^[1-9]\\d*$",
            "user_friendly": "Schema major version",
            "example": "4"
        },
        "schema_minor_version": {
            "description": "The minor version number of the schema.",
            "type": "integer",
            "pattern": "^\\d+$",
            "user_friendly": "Schema minor version",
            "example": "6"
        },
        "schema_type": {
            "description": "The type of the metadata schema entity.",
            "type": "string",
            "enum": [
                "protocol"
            ]
        },
        "provenance" : {
            "description": "Provenance information provided by the system.",
            "type": "object",
            "$ref": "system/provenance.json"
        },
         "protocol_core" : {
            "description": "Core protocol-level information.",
             "type": "object",
            "$ref": "core/protocol/protocol_core.json",
            "user_friendly": "Protocol core"
        },
        "method": {
            "description": "The method by which enrichment was achieved.",
            "type": "object",
            "$ref": "module/ontology/process_type_ontology.json",
            "user_friendly": "Enrichment method"
        },
        "markers": {
            "description": "A list of markers used to enrich for or against certain cells.",
            "type": "string",
            "example": "CD4+ CD8-; HLA-G+",
            "user_friendly": "Markers",
            "guidelines": "Format as a space-delimited list of markers with +/- where + means enriched for and - means enriched against."
        },
        "minimum_size": {
            "description": "Minimum cell or organelle size passing selection, in microns.",
            "type": "number",
            "maximum": 10000,
            "minimum": 0.01,
            "user_friendly": "Minimum size selected",
            "example": 70
        },
        "maximum_size": {
            "description": "Maximum cell or organelle size passing selection, in microns.",
            "type": "number",
            "maximum": 10000,
            "minimum": 0.01,
            "user_friendly": "Maximum size selected",
            "example": 90
        }
    }
}

=== HumanCellAtlas/metadata-schema/infrastructure_testing_files/dcp_metadata_testing_files/7b351f00-522f-49a9-8302-754eb076f979/metadata/enrichment_protocol/73001089-4129-4daf-81e7-aa47e05ca565_2021-03-16T16:15:23.551000Z.json
{"describedBy": "https://schema.humancellatlas.org/type/protocol/biomaterial_collection/3.1.0/enrichment_protocol", "schema_type": "protocol", "protocol_core": {"protocol_id": "EnrichmentProtocol_1", "protocol_name": "EnrichProt1", "protocol_description": "Test Enrichment Protocol", "publication_doi": "19.1191/293245", "protocols_io_doi": "10.17504/protocols.io.mgjc3un", "document": "my_cool_protocol.pdf"}, "method": {"text": "enzymatic dissociation", "ontology": "EFO:0009128", "ontology_label": "enzymatic dissociation"}, "markers": "CD4+ CD8+", "minimum_size": 70.0, "maximum_size": 90.0, "provenance": {"document_id": "73001089-4129-4daf-81e7-aa47e05ca565", "submission_date": "2021-03-16T16:15:23.551Z", "update_date": "2021-03-16T16:15:47.580Z", "schema_major_version": 3, "schema_minor_version": 1}}
